# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0005_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
