# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0006_display_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='display_image',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
