# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0007_auto_20171106_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='display_image',
            field=models.ImageField(upload_to='images/display/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
