# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0009_auto_20171107_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='display_image',
            field=models.ImageField(upload_to='display/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
