# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0010_auto_20171107_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='product_image',
        ),
    ]
