# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artstore', '0014_auto_20171109_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.AddField(
            model_name='product',
            name='artist_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artstore.Product'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='category_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artstore.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
